### ISSUE TITLE
Avoid volume mount

### ISSUE THREAD

**Issue by arthurrichards77** [StarlingUAS/FenswoodScenario#16]
Please could we drop the volume mounting of the Fenswood-specific resources?  I suggest instead that these could be built into the image, either creating a special `starling-fenswood-simhost` image as I have done [here](https://github.com/arthurrichards77/starling_simhost_fenswood) or by simply making the Fenswood model a standard component for Starling.  I like the suggestion of having one repo per container/image, but in the current set-up, this would get folded into the main Starling repo.

Rationale - I'd like for students to be able to get going on the Fenswood volcano project by just cloning and developing in one place.  My example is [here](https://github.com/arthurrichards77/fenswood_volcano_template).  All the necessary resources are then pulled from Docker hub, rather than mixed across local git clones and docker hub if we have the volume mount.

**Comment by mhl787156** [comment]
Yes I see how it would streamline things for just cloning and developing in one place. Especially if we do not expect a user to modify the environment. I can set up the automated building and pushing to dockerhub so that it can just be pulled. 

That being said, in order for the user to modify the drone model (add more sensors etc) the user will need to mount something at somepoint. I think that can happen in the same repository as the example drone controller code, but with the folder mounted into simhost similar to before. 
Either that, or we fix the drone and its capabilities (we have had students ask about the range of sensors available and how to simulate/use that data) and bake it into the 'environment'.

I would suggest PR-ing your Fork but i'm not sure if you forked or copied!
