### ISSUE TITLE
I seem to be sinking into the yellow stuff

### ISSUE THREAD

**Issue by arthurrichards77** [StarlingUAS/FenswoodScenario#17]
![Screenshot (3)](https://user-images.githubusercontent.com/9282037/148544293-e527d218-6156-4f32-bd38-66830ac3bc68.png)

Missing collision info?  So it's only a visual model?

**Comment by mhl787156** [comment]
Interesting, Technically there is Collision info being included into the link.

Looking at it, it looks like I've assigned a cylinder accidentally instead of a box... (https://github.com/StarlingUAS/FenswoodScenario/blob/77c8215f92ee231f4e6c06d922f06316db294911/fenswood/spawn_targets.py#L76) I wonder if thats an issue.

I think some further checks might be needed, we'll look into it.
